server:
  port: 9090
greeting: Hello World

spring:
  cloud:
    config:
      name: config-server
      enabled: true
      uri: http://localhost:8888
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8761/
