server:
  port: 9090
greeting: Hello World

spring:
  cloud:
    config:
      name: configserver
      enabled: true
      uri: http://localhost:8888
      discovery:
        service-id: config-server
